### ISSUE TITLE
`fromlatest.io` still errors on having `ARG` before `FROM`

### ISSUE THREAD

**Issue by hansbogert** [replicatedhq/dockerfilelint#135]
Currently, the linter gives warning of 'First Command Must Be FROM (Possible Bug)'. However, I think there is at least one exception:

In order to have access to build arguments in multiple stages, said build arguments should be declared in the outer scope of the Dockerfile, **before any `FROM` directives**

**Comment by deiga** [comment]
@hansbogert This should already be working, see https://github.com/replicatedhq/dockerfilelint/pull/105

**Comment by hansbogert** [comment]
strange, the online variant [variant](https://www.fromlatest.io/#/)  still shows this behaviour

**Comment by deiga** [comment]
My hunch would be, that the online variant is not using the newest version. It doesn't have the version listed anywhere, so hard to check

**Comment by deiga** [comment]
Could you reword the title to reflect that the issue is with the online variant? :)

**Comment by asears** [comment]
This still seems to be happening in <https://www.fromlatest.io/#/>

ARG is valid syntax before FROM as of https://github.com/moby/moby/pull/31352

**Comment by SimonHeimberg** [comment]
The online version seems to be updated. At least the following examples works. Can we close this issue?

```
ARG xxx

FROM ubuntu:bionic
```

**Comment by hansbogert** [comment]
@SimonHeimberg seems to work correctly indeed.
